spring:
  application:
    name: book-ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: tnamlong2132000@gmail.com
    password: uzidzajxmmcizuys
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 6868

jwt:
  secret-key: "supersecretkeysupersecretkeysupersecretkey123123123asdsdrfwqerqw"

app:
  reset-password:
    url: http://localhost:3000/reset-password?token=

cloudinary:
  cloud:
    name:
  api:
    key:
    secret:
