spring:
  application:
    name: book-ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 6868

jwt:
  secret-key: